### PR TITLE
Feature/4 patient creation view

### LINKED ISSUE #4: Patient creation view
## Feature Description
Create a patient creation view, where users add patient information (name, alias, DNI, birth date, address, gender, telephone, first intervention, name of technician (user) who cared for the patient, and observations)
## Motivation
This feature is necessary in order to allow users to create a new patient with its data
## Acceptance Criteria
- [ ] Criteria 1: Once a patient is created, display the detailed view of the patient
- [ ] Criteria 2: Input validation on telephone number, DNI, birth date, and possibly name
- [ ] Criteria 3: name of technician should be autocompleted with the name of the current logged in user, but it can be manually changed
## Additional Details
Subject to change in future meetings.

### PR DESCRIPTION
**Pull request by sebasruii**
# Description

The implemented feature is a modal form that allows the creation of a new beneficiary for ACAT. Since necessary backend functionality is still not implemented, I have used a mock API to perform POST requests. When backend endpoint becomes available, the endpoint will be updated. 

Client-side form validation is still yet to be implemented.
Error handling is also not implemented yet.

# How Has This Been Tested?

Since backend fucntionality is not currently available, I have tested only using mock responses.
In order to test the new form, you must browse to `/beneficiaries` and click on `Dar de alta`. The modal will then appear.
Once you click on submit, the response given by the mock API will redirect to `/beneficiaries/{id}`, where id refers to the id of the newly created Beneficiary. You will then be presented with a 404 error code, but that is normal, because the endpoint corresponds with the detailed page of a beneficiary, which is another feature to be implemented.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# Screenshot(If applies):
image

image

### CODE REVIEW

**Comment by sebasruii** [comment]
Hello @Manuelgruiz, I have noticed you've started testing before even reviewing the changes in this pull request. Please, before making any changes in this feature branch, it is indispensable that you leave your review and state that you are going to work on test through messages/comments/reviews in this PR. It is defined in our coding management policy.

Also, could you explain why a force-push was necessary?

**Comment by Manuelgruiz** [comment]
Hi @sebasruii ,
I apologize for the oversight. The review was actually done yesterday, but I forgot to leave a comment.  Thank you for your patience

Regarding the force-push, it was a mistake on my part. I did review the changes in the pull request, but I failed to comment on it. Everything seems to be in order. Thank you for bringing it to my attention.

**Review by Manuelgruiz — CHANGES_REQUESTED** [review]
Overall, the changes look great! 

The button that opens the modal could be made slightly larger to improve visibility and ensure that the text is easier to read.

**Comment by sebasruii** [comment]
There's no problem @Manuelgruiz, thank you for your review. That button is there only for displaying purposes, but will not be used in the final version of our app. That button is located/implemented in the "Beneficiaries listing". 
With that in mind, now I will resolve conflicts with `develop` and fix the current codacy issues.

**Comment by sebasruii** [comment]
Hello @Manuelgruiz, I hope this comment finds you well.
I have resolved all conflicts with the `develop` branch and I think this feature is ready to be merged.

**Review by Manuelgruiz — APPROVED** [review]
This is ready to merge.

**Pull request merged**
