### PR TITLE
feat: Add connection of interventions to the backend

### LINKED ISSUE #59: fix: Fix create intervention
## Bug Description
The create intervention button does not work and it is still not connected to backend. It is necessary that it works before the end of this sprint. Code is currently commented.

### PR DESCRIPTION
**Pull request by Ronald752**
# Description

In this PR, the error that did not allow to visualise the modal to create an intervention has been corrected, and the view to show all the interventions and their corresponding details has been connected to the backend.

To show the details of the interventions, the field showing the remarks has been modified, because when you show a very large text it did not fit.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Ronald752** [comment]
For the creation of the intervention, previously you must create a user which will be the technician (although you can really put which names because there is no check if it exists), in the name entry you must put the UUID of a patient that you have created, the one that MongoDB gives you.
Backend has already been notified to make an improvement on that, because it is not optimal that they have to remember that, also I suggested them to use the DNI of the patient.

**Comment by sebasruii** [comment]
> For the creation of the intervention, previously you must create a user which will be the technician (although you can really put which names because there is no check if it exists), in the name entry you must put the UUID of a patient that you have created, the one that MongoDB gives you. Backend has already been notified to make an improvement on that, because it is not optimal that they have to remember that, also I suggested them to use the DNI of the patient.

I think it is better if you request a list of all patients, and then select one of them based on name

**Comment by sebasruii** [comment]
Feature works well, And I've implemented the select. (https://react-select.com/home)

**Review by sebasruii — APPROVED** [review]
This is ready to be merged 👍🏻 good job!

**Pull request merged**
