### PR TITLE
feat: Modal interventions #2

### LINKED ISSUE #2: Detail view of interventions
## Feature Description
Create a modal where the details of an intervention are displayed, such as the date, the technician who attended the intervention, the reason and some observations.
## Motivation
This new modality is necessary as it provides a quick and easy way to access information on interventions.
## Acceptance Criteria
- [ ] Criteria 1: Clicking on each of the interventions should display a modal with detailed information.
- [ ] Criteria 2: The information should include: date, typology, technician, reason and remarks.
- [ ] Criteria 3: A delete button and an edit button should be included.
## Additional Details
The modal must be centred on the screen.

### PR DESCRIPTION
**Pull request by Ronald752**
# Description

A modal has been implemented to show the details of each intervention.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [x] Test A
- [x] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# Screenshot:

image

### CODE REVIEW

**Review by JaviGarc1a — CHANGES_REQUESTED** [review]
Hi, first of all try changing the CSS class to tailwind, leave only the essentials. Also change the file extensions from js to jsx.
In page.js styles are imported, but never used. I also think react-router dependencies are not necessary.
Finally, take a look [here](https://medium.com/@dtulpa16/next-js-modals-made-easy-7bdce15b2a5e) to improve the modal component.

**Comment by Ronald752** [comment]
I have made the modifications that were requested, it has also been adapted to the new components. In order to test its functioning a table with test values has been created, you have to click on the names and its corresponding modal will be shown.

**Review by JaviGarc1a — CHANGES_REQUESTED** [review]
It's pretty good, just a couple of changes. In the `interventions.map()` you make to show the interventions you use `i` as a name, it is preferable that you use intervention or something more descriptive, although that part would be done by someone else, we don't want you to keep using such a non-descriptive name. Also, I would add the x to close, being faithful to the design of the models.
image

**Comment by JaviGarc1a** [comment]
Now, the close button looks like this. It's not exactly the mockup, but it's the best I can leave it. I proceed to perform the tests for this view

image

**Comment by JaviGarc1a** [comment]
Coverage:
image

**Review by JaviGarc1a — APPROVED** [review]

**Pull request merged**
