### PR TITLE
Feature/36 login backend api

### LINKED ISSUE #36: feat: Consume backend API for Login/Logout, and entity creation
## Feature Description
The aim is to replace the current MockAPI usage in frontend with our backend API implementation for the current Login/logout and entity creation features.
## Motivation
Create a configurable connection with the backend
## Acceptance Criteria
- [x] Login/Logout and entity creation features make API calls to the URL provided by the developer through a configuration file

### PR DESCRIPTION
**Pull request by sebasruii**
# Description

Added support for API consumption when creating a new user or loging in. I am still working on the "beneficiary creation" API consumption, there are some issues regarding fields that will need to be addressed with the backend team before consuming their API

**For user creation**: I have implemented a function that creates a POST request with axios. For now, it only posts the data, as we should discuss the behaviour after a user is created. In my opinion, there are two alternatives:
1- The user is prompted with a pop-up windows that shows that the user has been created correctly.
2- The user is redirected to the users listing (whic has not been implemented yet)

**For login**: I have implemented a function that creates a POST request with axios. For now it only posts the data, as we should discuss where the user is redirected after successfully loging in. 

Error handling is still yet to be implemented in both features.
I have tested these changes with a local deployment of the backend.
A .env file is needed in order to define NEXT_PUBLIC_BASE_URL for the API URL.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sebasruii** [comment]
When trying to test the API connection, I've had multiple errors with the backend deployed in local, I kept getting CORS errors like the following:
`"Access to XMLHttpRequest at 'http://localhost:8080/api/v1/shared/user/' from origin 'http://localhost:3000/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."`
Following ourr backend deployment guide, I added `localhost:3000` to the BACKEND_CORS_ORIGINS .env variable, but it made no difference at all.
This happened when trying to make a POST petition from the frontend, specifically from a client rendered component. I suspect the error is due to the POST petition being made from the users browser and not from the server where the frontend is deployed. 
Finally, to test the changes I had to change the following line on `main.py` in the backend:
image
and from there, I could get it to work. This is something we may need to properly discuss with the backend team.

**Comment by sebasruii** [comment]
With respect to beneficiary creation, the current backend model (as defined by the API docs) expects:
image
Currently it seems like it requires id, registration_date and age as attributes in the request body, which should be autogenerated (in case of age, it should be derived from birth_date).
To keep up with the required data, I will need to modify the patient creation form to allow the user to input first_surname and second_surname. But one field that makes me doubt is the dossier_number, is that supposed to be input by the user? or auto-generated by the backend at creation time? @nicoloboo02

**Comment by nicoloboo02** [comment]
Good morning Fran. First of all, good work, I've seen that you've been making a lot of progress and in general, most things are very good. Great work. I'll proceed to list you regarding the doubts you have told me about.
1. I consider the best option when creating the user the popup.
2. The user should be redirected to the beneficiaries tab, as this is the main tab of the page.
Regarding the client side rendering, well corrected. I will communicate it to Backend. I would be grateful if you could communicate it to the rest of the frontend colleagues so that they know how to solve this error.
3. Regarding dossier number, tell Backend about it. I'm not sure of the answer either.
Thank you very much and good job, when everything is finished I will proceed to check it more thoroughly.

**Comment by sebasruii** [comment]
Hi @nicoloboo02, I've made the changes according to what we have discussed. Give it a check whenever you can 😃

**Review by nicoloboo02 — APPROVED** [review]
Good afternoon Fran. Everything works properly, good job!

**Pull request merged**
