### PR TITLE
Feature/1 add list appointments

### LINKED ISSUE #1: Add list appointments
## Feature Description
Create a list of ACAT appointments that allows visualizing the date,info of each appointment in a small box.
## Motivation
This new ACAT appointment list is necessary to enhance user experience by providing a quick and easy way to access information about appointments.
## Acceptance Criteria
- [x] Criteria 1: The list of appointments must show all of the appointments. 
- [x] Criteria 2: Each appointment must display the day it was scheduled.
- [x] Criteria 3: The name of the patient must appear alongside each appointment. 
## Additional Details
The list of appointments should be organized in a clear and orderly manner to facilitate searching and quick reference.

### PR DESCRIPTION
**Pull request by Manuelgruiz**
# Description
Added the list of appointments

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# Screenshot(If applies):

### CODE REVIEW

**Review by sebasruii — CHANGES_REQUESTED** [review]
Hello @Manuelgruiz, the listing looks good, but there are two things that could be improved:

1. The date tag inside the intervention card should be justified to the left, in order to be similar to the mockups
2. You should implement the functionality for fetching data with the Axios library. Since backend functionality might not be implemented yet, I reccomend that tou use MockAPI to create fake data and simulating the GET requests. The URL will then be updated as soos as backend is implemented. You can check f909e19ae34e0c2f5e0a9aa839c21e6ab167c3a2 to find how I implemented a request on another functionality.

**Comment by Manuelgruiz** [comment]
Hello @sebasruii 
I've made the requested changes yesterday

**Comment by Manuelgruiz** [comment]
Hello @sebasruii 
I just solved some future mistakes in Develop, they could have been avoided if in our methodology we made an order for the PRs, only your tests remain, but the configuration is done.

**Review by sebasruii — COMMENTED** [review]
Hello @Manuelgruiz 
Everything looks great, I would ask you to merge develop into this branch in order to keep up with the updates on some components (like the searchbar, which might cause some trouble on your view).

EDIT: Since I implemented the changes on the searchbar, I think it'd be better if I resolved the conflicts, before implementing the tests.

**Review by sebasruii — APPROVED** [review]
I have added tests and everything works great! this PR is ready to be merged 👍🏻

**Pull request merged**
