### PR TITLE
test: Upgrade tests #48

### PR DESCRIPTION
**Pull request by nicoloboo02**
# Description

A refactoring of all tests has been performed to increase code coverage
I am aware that code coverage is not 80%. Some of the missing functionality I don't see as necessary to test, and the rest I simply haven't found a way to test. 
Even so, coverage is up 30%.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Manuelgruiz — CHANGES_REQUESTED** [review]
First of all, congratulations! The tests looks much cleaner and clearer!

But i have some small suggestions 
If you check InterventionCardTest [ intervention_date: '2018-05-08T16:29:31.591Z' ] this should be only a date i tried to put the same value in the back but it gives me an error.                                  

I need your feedback since in the fetch of intervention, the base URL is set to '/appointment/' whereas in the backend it is '/intervention/'

**Comment by nicoloboo02** [comment]
Good morning @Manuelgruiz . If that is the only error you have detected, I would appreciate it if you would accept the pull request, as that change does not pertain to the implemented functionality, only to the tests. Thank you very much.

**Review by Manuelgruiz — APPROVED** [review]

**Comment by Manuelgruiz** [comment]
Okay, if that's the case, I'd be ready to merge

**Review by Ronald752 — APPROVED** [review]
You have done a great job.

**Pull request merged**
