### PR TITLE
Responsiveness app

### LINKED ISSUE #41: Join new components and adapt to old views
## Feature Description
The views correctly display all components and adapt correctly to different screen sizes.
## Motivation
To avoid getting errors in the develop branch when merge issues #30  and #31, this issue and associated branch has been created to fix those problems.
## Acceptance Criteria
- [ ] [Criteria 1: Views displayed correctly.
- [ ] [Criteria 2: Views are responsive.

### PR DESCRIPTION
**Pull request by JaviGarc1a**
# Description

App has been made fully responsive and refactored. Every single component has been modified. Everyone should check that your newest features has been correctly implemented. Otherwise, let us know about it with a detailed explanation of what is the issue and how to fix it.

# How Has This Been Tested?

Testing informal.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by nicoloboo02 — APPROVED** [review]
Incredible work, it works properly.

**Review by sebasruii — CHANGES_REQUESTED** [review]
Great job, I really like the new look for the app. There's just one thing that needs to be changed:
image
The birth date attribute for the patient creation form mut be named and identfied as `birth_date`, as that is the expected attribute name for backend API (must use an underscore instead of a hyphen)

**Review by Ronald752 — APPROVED** [review]
Incredible work, it works properly.

**Review by sebasruii — APPROVED** [review]
Everything great. Good job!

**Review by Manuelgruiz — APPROVED** [review]
Looks amazing!

**Pull request merged**
