### PR TITLE
Feature/34 connect to backend

### LINKED ISSUE #34: feat: Connect to backend
## Feature Description
This issue is focused on making the connection to the backend, specifically the detail sections. For example details of interventions, etc.

## Motivation
This is necessary for everything to work properly.

## Acceptance Criteria
- [ ] Criteria 1: All detail views will have to show all original data from the database.

### PR DESCRIPTION
**Pull request by Ronald752**
# Description

In this PR, it was required to connect all parts of the frontend that correspond to the details associated with an entity. Due to lack of implementation of views and some GET functions by the backend, only the connection to the backend to access the details of a beneficiary has been implemented. 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Ronald752** [comment]
At the moment backend does not include in the details of a beneficiary, the technician or the remarks, so the name field has been added for the moment, in order to make it work correctly.

**Comment by Ronald752** [comment]
It seems that the fields I mentioned above have already been added, but they are not mergeable, so I could not check it, I will modify the fields with the corresponding names. Attached is a Json image which I used as a guide.
image

**Comment by Ronald752** [comment]
In case backend has implemented both attributes.
In order to check the correct functioning of the detail view, you should follow the steps below:
1.Create a copy of the .env.example file.
2.Name the file .env
3.Create a beneficiary in backend.
4.Click on the first item in the list of beneficiaries.

It is important that you only select the first element of the list because the rest of the values will fail.
This is because the list values are from mockapi and the details are from the beneficiaries you have created in backend.

**Review by JMGarCas — CHANGES_REQUESTED** [review]
I was not able to run the backend, but looking at the code I have seen some issues:

- The PR description lacks information. It has to be more detailed.
- fetch.js needs error handling. Otherwise, in the event of an error, the app will crash
- There is commented code. You either use it or delete it

**Comment by Ronald752** [comment]
I have improved the description of this PR as you requested, I would like to ask you about the commented code you mention and I would like you to specify which one you are referring to, because from my part no commented line has been added and from the part I have reviewed I have not detected any commented line either.
If you are referring to the commented code in the create.jsx file, that will be modified when the POST method is implemented and the commented code will be removed.

**Review by sebasruii — CHANGES_REQUESTED** [review]
Hello @Ronald752, feature works as expected, but the error handling must be improved. No console.log should be present, as the user won't have a console to read said message.
image

- As of now, if I navigate to a beneficiary detail page that does not exist, it shows a blank page, which is not informative at all for the user. I would suggest that an alert is sent to the user, and after that, the user should be redirected to the beneficiaries list (a possible improvement would be to add a 404 page, but that should be discussed with the team).

- You can check the current error handling on login, and user creation, which is now on develop.
- Also, take a look at the ; at the end of line on the code. That does not follow our code style, your linter should help you correct it.

**Comment by sebasruii** [comment]
This could be useful documentation for your feature:
https://nextjs.org/docs/app/api-reference/functions/redirect

**Review by sebasruii — APPROVED** [review]
Works great 👍🏻

**Comment by sebasruii** [comment]
Since @JMGarCas  is not available this week, I'll be taking over and merge this PR

**Pull request merged**
