### PR TITLE
Feature/19 register intervention

### LINKED ISSUE #19: Appointment creation view
## Feature Description
Develop a feature to create an appointment registry that enables users to record details of appointments in a structured format.
## Motivation
This new appointment registry feature aims to streamline the process of documenting appointment information, enhancing organization and accessibility for users.
## Acceptance Criteria
- [ ] [Criteria 1: The appointment registry must allow users to input and store details an appointment.
- [ ] [Criteria 2: Each entry in the registry must include the date of the appointment.
- [ ] [Criteria 3: The name of the patient associated with each appointment must be included in the registry entry.
## Additional Details
The appointment registry should offer a user-friendly interface for inputting and viewing appointment details, ensuring ease of use and efficient management of appointment records.

### PR DESCRIPTION
**Pull request by Manuelgruiz**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# Screenshot(If applies):

### CODE REVIEW

**Review by sebasruii — CHANGES_REQUESTED** [review]
Everything works great, the only thing thats left to be implemented is the "Registrar intervención" button nex to the searchbar.

**Comment by Manuelgruiz** [comment]
I'm going to implement the connection modal search bar in the next sprint because we need to specify how we're going to make the connections

**Comment by sebasruii** [comment]
Hello @Manuelgruiz, here are some issues to be resolved before starting the testing phase for this feature:

1. Your modal should follow the styles defined in the mockup for this feature. Here you have a screenshot for reference:
image
The icons for each input should be inside. You can check the modal for creating a new beneficiary for a reference (or the login screen)
It is also important for the buttons to follow the styles.
2. Although backend implementation for handling POST request may not be implemented yet, it is necessary that you implement functionality to perform such request. You can use MockAPI for said implmementantion, or even mock data, but the Axios implementation is required.
3. I suggest that you base this modal implementation on the base modal provided by Nico. You can check the modal for creating a new beneficiary for reference. Currently, this modal relies on changing the URL to be shown, but that is not a necessary thing.
4. Another possible improvement to this feature would be that, when a intervention is registered, it loads the details of said newly created intervention.

**Comment by Manuelgruiz** [comment]
@sebasruii  Hello Fran, I don't know if you have noticed that the PR is ready for review.

**Comment by Manuelgruiz** [comment]
I suggest using the same changes I made to link the sidebar with  the create beneficiaries modal.

**Review by sebasruii — APPROVED** [review]
After reviewing, everything is correctly implemente. Good job @Manuelgruiz 👍🏻

**Pull request merged**
